namespace ROMSIS_CRM.frmForms
{
    using DevExpress.Utils;
    using DevExpress.XtraPrinting;
    using DevExpress.XtraPrinting.BarCode;
    using DevExpress.XtraReports.UI;
    using ROMSIS_CRM.dtsRBS;
    using System;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Drawing.Printing;

    public class prtQuotation : XtraReport
    {
        public XRLabel _lblAlici;
        public XRLabel _lblEmail_;
        public XRLabel _lblFax;
        public XRLabel _lblGonderen;
        public XRLabel _lblIlgiliKisi;
        public XRLabel _lblMail;
        public XRLabel _lblTalepNo;
        public XRLabel _lblTarih;
        public XRLabel _lblTeklifNo;
        public XRLabel _lblTelefon;
        public XRLabel _lblTelefon_;
        private BottomMarginBand BottomMargin;
        private IContainer components = null;
        private DetailBand Detail;
        private DetailBand Detail1;
        private DetailReportBand DetailReport;
        public dstQuotation dstQuotation1;
        private GroupHeaderBand GroupHeader1;
        private GroupHeaderBand GroupHeader2;
        public XRLabel lblAlici;
        public XRTableCell lblDeliveryCost;
        public XRLabel lblFax;
        public XRLabel lblGonderen_;
        public XRLabel lblIlgiliKisi;
        public XRTableCell lblIndirim;
        public XRTableCell lblKargoBedeli;
        public XRLabel lblMail;
        public XRLabel lblMail_;
        public XRLabel lblNot;
        public XRLabel lblNot_;
        public XRLabel lblNotIkiNokta;
        public XRLabel lblTalepNo;
        public XRLabel lblTarih_;
        public XRLabel lblTeklifNo;
        public XRLabel lblTelefon;
        public XRLabel lblTelefon_;
        public XRTableCell lblToplam;
        private PageFooterBand PageFooter;
        private PageHeaderBand PageHeader;
        private ReportFooterBand ReportFooter;
        private TopMarginBand TopMargin;
        private XRBarCode xrBarCode1;
        public XRTableCell xrBrut;
        public XRTableCell xrDegisken1;
        public XRTableCell xrDegisken2;
        public XRLabel xrGecerlilikSuresi;
        public XRLabel xrGecerlilikSuresi_;
        public XRLabel xrHesapNo;
        public XRLabel xrIbanNo;
        public XRTableCell xrKdv;
        public XRTableCell xrKodu;
        public XRLabel xrKurAdi;
        private XRLabel xrLabel1;
        private XRLabel xrLabel10;
        private XRLabel xrLabel11;
        private XRLabel xrLabel12;
        private XRLabel xrLabel13;
        private XRLabel xrLabel14;
        private XRLabel xrLabel15;
        private XRLabel xrLabel16;
        private XRLabel xrLabel17;
        private XRLabel xrLabel18;
        public XRLabel xrLabel2;
        public XRTableCell xrLabel22;
        private XRTableCell xrLabel23;
        public XRLabel xrLabel25;
        public XRLabel xrLabel26;
        public XRLabel xrLabel3;
        public XRLabel xrLabel30;
        public XRLabel xrLabel32;
        public XRLabel xrLabel37;
        public XRLabel xrLabel4;
        private XRLabel xrLabel41;
        public XRTableCell xrLabel5;
        private XRLabel xrLabel6;
        private XRLabel xrLabel9;
        private XRLine xrLine1;
        private XRLine xrLine3;
        public XRTableCell xrNetToplam;
        public XRLabel xrOdemeSekli;
        public XRLabel xrOdemeSekli_;
        public XRTableCell xrOnay;
        private XRPageInfo xrPageInfo1;
        public XRTableCell xrPaketSaiyisi;
        public XRTableCell xrPakettekiUrunMiktari;
        private XRPictureBox xrPictureBox1;
        private XRPictureBox xrPictureBox2;
        public XRLabel xrSozlesmeBaslik;
        public XRLabel xrSozlesmeKosullari;
        private XRTable xrTable1;
        public XRTable xrTable2;
        public XRTable xrTable3;
        private XRTable xrTable4;
        public XRTable xrTable5;
        private XRTableCell xrTableCell1;
        private XRTableCell xrTableCell10;
        public XRTableCell xrTableCell11;
        public XRTableCell xrTableCell12;
        public XRTableCell xrTableCell13;
        public XRTableCell xrTableCell14;
        public XRTableCell xrTableCell15;
        private XRTableCell xrTableCell16;
        public XRTableCell xrTableCell17;
        private XRTableCell xrTableCell18;
        public XRTableCell xrTableCell19;
        private XRTableCell xrTableCell2;
        public XRTableCell xrTableCell20;
        public XRTableCell xrTableCell21;
        private XRTableCell xrTableCell22;
        private XRTableCell xrTableCell23;
        private XRTableCell xrTableCell25;
        private XRTableCell xrTableCell27;
        private XRTableCell xrTableCell29;
        public XRTableCell xrTableCell3;
        private XRTableCell xrTableCell4;
        public XRTableCell xrTableCell5;
        public XRTableCell xrTableCell6;
        public XRTableCell xrTableCell7;
        public XRTableCell xrTableCell8;
        public XRTableCell xrTableCell9;
        private XRTableRow xrTableRow1;
        private XRTableRow xrTableRow11;
        private XRTableRow xrTableRow12;
        private XRTableRow xrTableRow2;
        private XRTableRow xrTableRow3;
        private XRTableRow xrTableRow4;
        private XRTableRow xrTableRow5;
        private XRTableRow xrTableRow6;
        private XRTableRow xrTableRow7;
        private XRTableRow xrTableRow8;
        private XRTableRow xrTableRow9;
        public XRTableCell xrTeslimat;
        public XRLabel xrToplamAgirlik;
        public XRLabel xrToplamAgirlik_;
        public XRTableCell xrToplamFiyat;
        public XRTableCell xrToplamUrunMiktari;
        public XRTableCell xrUreticiAdi;
        public XRTableCell xrUreticiKodu;

        public prtQuotation()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(prtQuotation));
            QRCodeGenerator generator = new QRCodeGenerator();
            XRSummary summary = new XRSummary();
            XRSummary summary2 = new XRSummary();
            XRSummary summary3 = new XRSummary();
            XRSummary summary4 = new XRSummary();
            this.Detail = new DetailBand();
            this.xrTable4 = new XRTable();
            this.xrTableRow6 = new XRTableRow();
            this.xrTableCell2 = new XRTableCell();
            this.xrTableCell3 = new XRTableCell();
            this.xrTableCell10 = new XRTableCell();
            this.xrLabel5 = new XRTableCell();
            this.xrTableCell5 = new XRTableCell();
            this.xrTableCell6 = new XRTableCell();
            this.xrTableCell7 = new XRTableCell();
            this.xrTableCell8 = new XRTableCell();
            this.xrTableCell9 = new XRTableCell();
            this.xrLabel22 = new XRTableCell();
            this.xrLabel23 = new XRTableCell();
            this.xrTableCell12 = new XRTableCell();
            this.xrTable1 = new XRTable();
            this.xrTableRow1 = new XRTableRow();
            this.xrTableCell1 = new XRTableCell();
            this.xrKodu = new XRTableCell();
            this.xrTableCell4 = new XRTableCell();
            this.xrDegisken1 = new XRTableCell();
            this.xrUreticiKodu = new XRTableCell();
            this.xrUreticiAdi = new XRTableCell();
            this.xrPakettekiUrunMiktari = new XRTableCell();
            this.xrPaketSaiyisi = new XRTableCell();
            this.xrToplamUrunMiktari = new XRTableCell();
            this.xrDegisken2 = new XRTableCell();
            this.xrToplamFiyat = new XRTableCell();
            this.xrTeslimat = new XRTableCell();
            this.TopMargin = new TopMarginBand();
            this.xrPageInfo1 = new XRPageInfo();
            this.BottomMargin = new BottomMarginBand();
            this.dstQuotation1 = new dstQuotation();
            this.xrLine1 = new XRLine();
            this.PageHeader = new PageHeaderBand();
            this.xrPictureBox2 = new XRPictureBox();
            this.xrPictureBox1 = new XRPictureBox();
            this.xrBarCode1 = new XRBarCode();
            this.PageFooter = new PageFooterBand();
            this.xrLabel6 = new XRLabel();
            this.xrLabel2 = new XRLabel();
            this.xrTable5 = new XRTable();
            this.xrTableRow7 = new XRTableRow();
            this.xrTableCell11 = new XRTableCell();
            this.xrLabel1 = new XRLabel();
            this.xrLine3 = new XRLine();
            this.xrTable2 = new XRTable();
            this.xrTableRow2 = new XRTableRow();
            this.xrOnay = new XRTableCell();
            this.xrSozlesmeKosullari = new XRLabel();
            this.xrSozlesmeBaslik = new XRLabel();
            this.GroupHeader1 = new GroupHeaderBand();
            this.lblTalepNo = new XRLabel();
            this.xrLabel41 = new XRLabel();
            this._lblTalepNo = new XRLabel();
            this.lblTelefon_ = new XRLabel();
            this.lblTarih_ = new XRLabel();
            this.lblGonderen_ = new XRLabel();
            this.lblMail_ = new XRLabel();
            this.xrLabel18 = new XRLabel();
            this.xrLabel15 = new XRLabel();
            this.xrLabel16 = new XRLabel();
            this.xrLabel17 = new XRLabel();
            this._lblTelefon_ = new XRLabel();
            this._lblTarih = new XRLabel();
            this._lblGonderen = new XRLabel();
            this._lblEmail_ = new XRLabel();
            this.lblFax = new XRLabel();
            this.lblMail = new XRLabel();
            this.lblTeklifNo = new XRLabel();
            this.lblIlgiliKisi = new XRLabel();
            this.lblAlici = new XRLabel();
            this.lblTelefon = new XRLabel();
            this.xrLabel14 = new XRLabel();
            this.xrLabel13 = new XRLabel();
            this.xrLabel12 = new XRLabel();
            this.xrLabel11 = new XRLabel();
            this.xrLabel10 = new XRLabel();
            this.xrLabel9 = new XRLabel();
            this._lblFax = new XRLabel();
            this._lblMail = new XRLabel();
            this._lblTelefon = new XRLabel();
            this._lblIlgiliKisi = new XRLabel();
            this._lblAlici = new XRLabel();
            this._lblTeklifNo = new XRLabel();
            this.xrGecerlilikSuresi = new XRLabel();
            this.xrLabel30 = new XRLabel();
            this.xrGecerlilikSuresi_ = new XRLabel();
            this.ReportFooter = new ReportFooterBand();
            this.lblNot = new XRLabel();
            this.lblNotIkiNokta = new XRLabel();
            this.lblNot_ = new XRLabel();
            this.xrIbanNo = new XRLabel();
            this.xrLabel4 = new XRLabel();
            this.xrLabel3 = new XRLabel();
            this.xrKurAdi = new XRLabel();
            this.xrLabel25 = new XRLabel();
            this.xrHesapNo = new XRLabel();
            this.xrToplamAgirlik_ = new XRLabel();
            this.xrLabel26 = new XRLabel();
            this.xrToplamAgirlik = new XRLabel();
            this.xrTable3 = new XRTable();
            this.xrTableRow11 = new XRTableRow();
            this.xrTableCell22 = new XRTableCell();
            this.lblToplam = new XRTableCell();
            this.xrTableCell27 = new XRTableCell();
            this.xrTableRow12 = new XRTableRow();
            this.xrTableCell25 = new XRTableCell();
            this.lblIndirim = new XRTableCell();
            this.xrTableCell29 = new XRTableCell();
            this.xrTableRow8 = new XRTableRow();
            this.xrTableCell13 = new XRTableCell();
            this.lblKargoBedeli = new XRTableCell();
            this.xrTableCell21 = new XRTableCell();
            this.xrTableRow9 = new XRTableRow();
            this.xrTableCell14 = new XRTableCell();
            this.lblDeliveryCost = new XRTableCell();
            this.xrTableCell23 = new XRTableCell();
            this.xrTableRow3 = new XRTableRow();
            this.xrNetToplam = new XRTableCell();
            this.xrTableCell17 = new XRTableCell();
            this.xrTableCell15 = new XRTableCell();
            this.xrTableRow4 = new XRTableRow();
            this.xrKdv = new XRTableCell();
            this.xrTableCell19 = new XRTableCell();
            this.xrTableCell16 = new XRTableCell();
            this.xrTableRow5 = new XRTableRow();
            this.xrBrut = new XRTableCell();
            this.xrTableCell20 = new XRTableCell();
            this.xrTableCell18 = new XRTableCell();
            this.xrLabel37 = new XRLabel();
            this.xrOdemeSekli_ = new XRLabel();
            this.xrLabel32 = new XRLabel();
            this.xrOdemeSekli = new XRLabel();
            this.DetailReport = new DetailReportBand();
            this.Detail1 = new DetailBand();
            this.GroupHeader2 = new GroupHeaderBand();
            this.xrTable4.BeginInit();
            this.xrTable1.BeginInit();
            this.dstQuotation1.BeginInit();
            this.xrTable5.BeginInit();
            this.xrTable2.BeginInit();
            this.xrTable3.BeginInit();
            this.BeginInit();
            this.Detail.Dpi = 254f;
            this.Detail.HeightF = 0f;
            this.Detail.Name = "Detail";
            this.Detail.Padding = new PaddingInfo(0, 0, 0, 0, 254f);
            this.Detail.TextAlignment = TextAlignment.TopLeft;
            this.xrTable4.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrTable4.BorderWidth = 1f;
            this.xrTable4.Dpi = 254f;
            this.xrTable4.Font = new Font("Calibri", 8f);
            this.xrTable4.LocationFloat = new PointFloat(0.9999959f, 0f);
            this.xrTable4.Name = "xrTable4";
            XRTableRow[] rows = new XRTableRow[] { this.xrTableRow6 };
            this.xrTable4.Rows.AddRange(rows);
            this.xrTable4.SizeF = new SizeF(2754.062f, 50.00002f);
            this.xrTable4.StylePriority.UseBorders = false;
            this.xrTable4.StylePriority.UseBorderWidth = false;
            this.xrTable4.StylePriority.UseFont = false;
            this.xrTable4.StylePriority.UseTextAlignment = false;
            this.xrTable4.TextAlignment = TextAlignment.MiddleCenter;
            XRTableCell[] cells = new XRTableCell[] { this.xrTableCell2, this.xrTableCell3, this.xrTableCell10, this.xrLabel5, this.xrTableCell5, this.xrTableCell6, this.xrTableCell7, this.xrTableCell8, this.xrTableCell9, this.xrLabel22, this.xrLabel23, this.xrTableCell12 };
            this.xrTableRow6.Cells.AddRange(cells);
            this.xrTableRow6.Dpi = 254f;
            this.xrTableRow6.Name = "xrTableRow6";
            this.xrTableRow6.Weight = 1.0;
            XRBinding[] bindings = new XRBinding[] { new XRBinding("Text", null, "dtQuotation.No") };
            this.xrTableCell2.DataBindings.AddRange(bindings);
            this.xrTableCell2.Dpi = 254f;
            this.xrTableCell2.Name = "xrTableCell2";
            this.xrTableCell2.Weight = 0.06755623019288369;
            XRBinding[] bindingArray2 = new XRBinding[] { new XRBinding("Text", null, "dtQuotation.RsCodu") };
            //this.xrTableCell3.DataBindings.AddRange(bindingArray2);
            this.xrTableCell3.Dpi = 254f;
            this.xrTableCell3.Name = "xrTableCell3";
            this.xrTableCell3.Padding = new PaddingInfo(8, 0, 0, 0, 254f);
            this.xrTableCell3.StylePriority.UsePadding = false;
            this.xrTableCell3.StylePriority.UseTextAlignment = false;
            this.xrTableCell3.TextAlignment = TextAlignment.MiddleLeft;
            this.xrTableCell3.Weight = 0.272969006681638;
            XRBinding[] bindingArray3 = new XRBinding[] { new XRBinding("Text", null, "dtQuotation.IE") };
            this.xrTableCell10.DataBindings.AddRange(bindingArray3);
            this.xrTableCell10.Dpi = 254f;
            this.xrTableCell10.Name = "xrTableCell10";
            this.xrTableCell10.Text = "xrTableCell10";
            this.xrTableCell10.Weight = 0.14683708196572884;
            this.xrLabel5.Dpi = 254f;
            this.xrLabel5.Name = "xrLabel5";
            this.xrLabel5.Padding = new PaddingInfo(8, 0, 0, 0, 254f);
            this.xrLabel5.StylePriority.UsePadding = false;
            this.xrLabel5.StylePriority.UseTextAlignment = false;
            this.xrLabel5.TextAlignment = TextAlignment.MiddleLeft;
            this.xrLabel5.Weight = 0.4244285718920896;
            this.xrLabel5.WordWrap = false;
            XRBinding[] bindingArray4 = new XRBinding[] { new XRBinding("Text", null, "dtQuotation.UreticiKodu") };
            this.xrTableCell5.DataBindings.AddRange(bindingArray4);
            this.xrTableCell5.Dpi = 254f;
            this.xrTableCell5.Name = "xrTableCell5";
            this.xrTableCell5.Padding = new PaddingInfo(8, 0, 0, 0, 254f);
            this.xrTableCell5.StylePriority.UsePadding = false;
            this.xrTableCell5.StylePriority.UseTextAlignment = false;
            this.xrTableCell5.TextAlignment = TextAlignment.MiddleLeft;
            this.xrTableCell5.Weight = 0.45312684945439308;
            XRBinding[] bindingArray5 = new XRBinding[] { new XRBinding("Text", null, "dtQuotation.UreticiAdi") };
            this.xrTableCell6.DataBindings.AddRange(bindingArray5);
            this.xrTableCell6.Dpi = 254f;
            this.xrTableCell6.Name = "xrTableCell6";
            this.xrTableCell6.Padding = new PaddingInfo(8, 0, 0, 0, 254f);
            this.xrTableCell6.StylePriority.UsePadding = false;
            this.xrTableCell6.StylePriority.UseTextAlignment = false;
            this.xrTableCell6.TextAlignment = TextAlignment.MiddleLeft;
            this.xrTableCell6.Weight = 0.30489867187665409;
            this.xrTableCell6.WordWrap = false;
            this.xrTableCell7.Dpi = 254f;
            this.xrTableCell7.Name = "xrTableCell7";
            this.xrTableCell7.Text = "[PakettekiUrunMiktari] / [Unit]";
            this.xrTableCell7.Weight = 0.27032072098192017;
            XRBinding[] bindingArray6 = new XRBinding[] { new XRBinding("Text", null, "dtQuotation.PaketSayisi") };
            this.xrTableCell8.DataBindings.AddRange(bindingArray6);
            this.xrTableCell8.Dpi = 254f;
            this.xrTableCell8.Name = "xrTableCell8";
            this.xrTableCell8.Weight = 0.17028804094452638;
            XRBinding[] bindingArray7 = new XRBinding[] { new XRBinding("Text", null, "dtQuotation.ToplamUrunMiktari") };
            this.xrTableCell9.DataBindings.AddRange(bindingArray7);
            this.xrTableCell9.Dpi = 254f;
            this.xrTableCell9.Name = "xrTableCell9";
            this.xrTableCell9.Weight = 0.20085567759514891;
            this.xrLabel22.Dpi = 254f;
            this.xrLabel22.Name = "xrLabel22";
            this.xrLabel22.Text = "[BirimAdetFiyati!f3] [SINGS] ";
            this.xrLabel22.Weight = 0.24135513860356056;
            this.xrLabel23.Dpi = 254f;
            this.xrLabel23.Name = "xrLabel23";
            this.xrLabel23.Padding = new PaddingInfo(0, 10, 0, 0, 254f);
            this.xrLabel23.StylePriority.UsePadding = false;
            this.xrLabel23.StylePriority.UseTextAlignment = false;
            this.xrLabel23.Text = "[KDVSIZT!f3] [SINGS] ";
            this.xrLabel23.TextAlignment = TextAlignment.MiddleRight;
            this.xrLabel23.Weight = 0.26570714744534851;
            XRBinding[] bindingArray8 = new XRBinding[] { new XRBinding("Text", null, "dtQuotation.TeslimatIsGunu") };
            this.xrTableCell12.DataBindings.AddRange(bindingArray8);
            this.xrTableCell12.Dpi = 254f;
            this.xrTableCell12.Multiline = true;
            this.xrTableCell12.Name = "xrTableCell12";
            this.xrTableCell12.Weight = 0.23493986901685235;
            this.xrTable1.BackColor = Color.Gainsboro;
            this.xrTable1.Borders = BorderSide.All;
            this.xrTable1.BorderWidth = 1f;
            this.xrTable1.Dpi = 254f;
            this.xrTable1.Font = new Font("Calibri", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.xrTable1.LocationFloat = new PointFloat(1f, 0f);
            this.xrTable1.Name = "xrTable1";
            XRTableRow[] rowArray2 = new XRTableRow[] { this.xrTableRow1 };
            this.xrTable1.Rows.AddRange(rowArray2);
            this.xrTable1.SizeF = new SizeF(2754.057f, 101.4792f);
            this.xrTable1.StylePriority.UseBackColor = false;
            this.xrTable1.StylePriority.UseBorders = false;
            this.xrTable1.StylePriority.UseBorderWidth = false;
            this.xrTable1.StylePriority.UseFont = false;
            this.xrTable1.StylePriority.UseTextAlignment = false;
            this.xrTable1.TextAlignment = TextAlignment.MiddleCenter;
            XRTableCell[] cellArray2 = new XRTableCell[] { this.xrTableCell1, this.xrKodu, this.xrTableCell4, this.xrDegisken1, this.xrUreticiKodu, this.xrUreticiAdi, this.xrPakettekiUrunMiktari, this.xrPaketSaiyisi, this.xrToplamUrunMiktari, this.xrDegisken2, this.xrToplamFiyat, this.xrTeslimat };
            this.xrTableRow1.Cells.AddRange(cellArray2);
            this.xrTableRow1.Dpi = 254f;
            this.xrTableRow1.Name = "xrTableRow1";
            this.xrTableRow1.Weight = 0.6998561570799624;
            this.xrTableCell1.Dpi = 254f;
            this.xrTableCell1.Name = "xrTableCell1";
            this.xrTableCell1.Text = "No";
            this.xrTableCell1.Weight = 0.06755623019288369;
            this.xrKodu.Dpi = 254f;
            this.xrKodu.Name = "xrKodu";
            this.xrKodu.Text = "RS Kodu";
            this.xrKodu.Weight = 0.27284326767221834;
            this.xrTableCell4.Dpi = 254f;
            this.xrTableCell4.Multiline = true;
            this.xrTableCell4.Name = "xrTableCell4";
            this.xrTableCell4.Text = "Durum";
            this.xrTableCell4.Weight = 0.14678281283471659;
            this.xrDegisken1.Dpi = 254f;
            this.xrDegisken1.Name = "xrDegisken1";
            this.xrDegisken1.Text = "\x00dcr\x00fcn A\x00e7ıklaması";
            this.xrDegisken1.Weight = 0.42524150701761171;
            this.xrUreticiKodu.Dpi = 254f;
            this.xrUreticiKodu.Name = "xrUreticiKodu";
            this.xrUreticiKodu.Text = "\x00dcretici Kodu";
            this.xrUreticiKodu.Weight = 0.45344376301910105;
            this.xrUreticiAdi.Dpi = 254f;
            this.xrUreticiAdi.Name = "xrUreticiAdi";
            this.xrUreticiAdi.Text = "\x00dcretici Adı";
            this.xrUreticiAdi.Weight = 0.30511219163673575;
            this.xrPakettekiUrunMiktari.Dpi = 254f;
            this.xrPakettekiUrunMiktari.Multiline = true;
            this.xrPakettekiUrunMiktari.Name = "xrPakettekiUrunMiktari";
            this.xrPakettekiUrunMiktari.Text = "1 Paketteki \r\n\x00dcr\x00fcn Miktarı";
            this.xrPakettekiUrunMiktari.Weight = 0.27050933858408038;
            this.xrPaketSaiyisi.Dpi = 254f;
            this.xrPaketSaiyisi.Multiline = true;
            this.xrPaketSaiyisi.Name = "xrPaketSaiyisi";
            this.xrPaketSaiyisi.Text = "Paket\r\nSayısı";
            this.xrPaketSaiyisi.Weight = 0.16815713329477997;
            this.xrToplamUrunMiktari.Dpi = 254f;
            this.xrToplamUrunMiktari.Multiline = true;
            this.xrToplamUrunMiktari.Name = "xrToplamUrunMiktari";
            this.xrToplamUrunMiktari.Text = "Top \x00dcr\x00fcn\r\nMiktarı";
            this.xrToplamUrunMiktari.Weight = 0.20324622222084804;
            this.xrDegisken2.Dpi = 254f;
            this.xrDegisken2.Multiline = true;
            this.xrDegisken2.Name = "xrDegisken2";
            this.xrDegisken2.Text = "Birim Paket \r\nFiyatı";
            this.xrDegisken2.Weight = 0.24152392249043564;
            this.xrToplamFiyat.Dpi = 254f;
            this.xrToplamFiyat.Name = "xrToplamFiyat";
            this.xrToplamFiyat.Text = "Toplam Fiyat";
            this.xrToplamFiyat.Weight = 0.26288585188681268;
            this.xrTeslimat.Dpi = 254f;
            this.xrTeslimat.Multiline = true;
            this.xrTeslimat.Name = "xrTeslimat";
            this.xrTeslimat.Text = "Teslimat \r\n(İş G\x00fcn\x00fc)";
            this.xrTeslimat.Weight = 0.23811021213883266;
            XRControl[] controls = new XRControl[] { this.xrPageInfo1 };
            this.TopMargin.Controls.AddRange(controls);
            this.TopMargin.Dpi = 254f;
            this.TopMargin.HeightF = 106.045f;
            this.TopMargin.Name = "TopMargin";
            this.TopMargin.Padding = new PaddingInfo(0, 0, 0, 0, 254f);
            this.TopMargin.TextAlignment = TextAlignment.TopLeft;
            this.xrPageInfo1.Dpi = 254f;
            this.xrPageInfo1.Font = new Font("Calibri", 9f, FontStyle.Underline | FontStyle.Bold, GraphicsUnit.Point, 0);
            this.xrPageInfo1.Format = "{0} / {1}";
            this.xrPageInfo1.LocationFloat = new PointFloat(1111.25f, 63.5f);
            this.xrPageInfo1.Name = "xrPageInfo1";
            this.xrPageInfo1.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrPageInfo1.SizeF = new SizeF(553.8811f, 42.545f);
            this.xrPageInfo1.StylePriority.UseFont = false;
            this.xrPageInfo1.StylePriority.UseTextAlignment = false;
            this.xrPageInfo1.TextAlignment = TextAlignment.TopCenter;
            this.BottomMargin.Dpi = 254f;
            this.BottomMargin.HeightF = 73f;
            this.BottomMargin.Name = "BottomMargin";
            this.BottomMargin.Padding = new PaddingInfo(0, 0, 0, 0, 254f);
            this.BottomMargin.TextAlignment = TextAlignment.TopLeft;
            this.dstQuotation1.DataSetName = "dstQuotation";
            this.dstQuotation1.SchemaSerializationMode = SchemaSerializationMode.IncludeSchema;
            this.xrLine1.Dpi = 254f;
            this.xrLine1.LineWidth = 4;
            this.xrLine1.LocationFloat = new PointFloat(1f, 156.3158f);
            this.xrLine1.Name = "xrLine1";
            this.xrLine1.SizeF = new SizeF(2754.062f, 6.22551f);
            XRControl[] controlArray2 = new XRControl[] { this.xrPictureBox2, this.xrPictureBox1, this.xrLine1 };
            this.PageHeader.Controls.AddRange(controlArray2);
            this.PageHeader.Dpi = 254f;
            this.PageHeader.HeightF = 162.5413f;
            this.PageHeader.Name = "PageHeader";
            this.xrPictureBox2.Dpi = 254f;
            //            this.xrPictureBox2.Image = (Image) manager.GetObject("xrPictureBox2.Image");
            this.xrPictureBox2.LocationFloat = new PointFloat(2087f, 0f);
            this.xrPictureBox2.Name = "xrPictureBox2";
            this.xrPictureBox2.SizeF = new SizeF(667.0615f, 156.3158f);
            this.xrPictureBox2.Sizing = ImageSizeMode.ZoomImage;
            this.xrPictureBox1.Dpi = 254f;
            //          this.xrPictureBox1.Image = (Image) manager.GetObject("xrPictureBox1.Image");
            this.xrPictureBox1.LocationFloat = new PointFloat(0.004150391f, 0f);
            this.xrPictureBox1.Name = "xrPictureBox1";
            this.xrPictureBox1.SizeF = new SizeF(889.4167f, 156.3158f);
            this.xrPictureBox1.Sizing = ImageSizeMode.ZoomImage;
            this.xrBarCode1.AutoModule = true;
            this.xrBarCode1.Dpi = 254f;
            this.xrBarCode1.LocationFloat = new PointFloat(2482.479f, 400.0037f);
            this.xrBarCode1.Module = 5.08f;
            this.xrBarCode1.Name = "xrBarCode1";
            this.xrBarCode1.Padding = new PaddingInfo(0x19, 0x19, 0, 0, 254f);
            this.xrBarCode1.ShowText = false;
            this.xrBarCode1.SizeF = new SizeF(192.5212f, 156.3158f);
            generator.CompactionMode = QRCodeCompactionMode.Byte;
            generator.Version = QRCodeVersion.Version2;
            this.xrBarCode1.Symbology = generator;
            this.xrBarCode1.Text = "http://tr.rsdelivers.com/";
            XRControl[] controlArray3 = new XRControl[] { this.xrLabel6, this.xrLabel2, this.xrTable5, this.xrLabel1, this.xrLine3, this.xrBarCode1, this.xrTable2, this.xrSozlesmeKosullari, this.xrSozlesmeBaslik };
            this.PageFooter.Controls.AddRange(controlArray3);
            this.PageFooter.Dpi = 254f;
            this.PageFooter.HeightF = 556.3195f;
            this.PageFooter.Name = "PageFooter";
            this.xrLabel6.Dpi = 254f;
            this.xrLabel6.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.xrLabel6.LocationFloat = new PointFloat(744.4797f, 314.8163f);
            this.xrLabel6.Name = "xrLabel6";
            this.xrLabel6.NavigateUrl = "http://tr.rsdelivers.com/CompanyInfo/ConditionsOfSale.aspx";
            this.xrLabel6.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel6.SizeF = new SizeF(296.3334f, 37.15009f);
            this.xrLabel6.StylePriority.UseFont = false;
            this.xrLabel6.Target = "_self";
            this.xrLabel6.Text = "Satış S\x00f6zleşmesi";
            this.xrLabel2.Dpi = 254f;
            this.xrLabel2.Font = new Font("Calibri", 8f);
            this.xrLabel2.LocationFloat = new PointFloat(0.9999959f, 305.9413f);
            this.xrLabel2.Multiline = true;
            this.xrLabel2.Name = "xrLabel2";
            this.xrLabel2.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrLabel2.SizeF = new SizeF(743.4797f, 53.02512f);
            this.xrLabel2.StylePriority.UseFont = false;
            this.xrLabel2.StylePriority.UsePadding = false;
            this.xrLabel2.StylePriority.UseTextAlignment = false;
            this.xrLabel2.Text = "Satış koşullarımız hakkında ayrıntılı bilgi edinmek i\x00e7in tıklayınız. ";
            this.xrLabel2.TextAlignment = TextAlignment.TopLeft;
            this.xrTable5.Borders = BorderSide.Right | BorderSide.Top | BorderSide.Left;
            this.xrTable5.BorderWidth = 3f;
            this.xrTable5.Dpi = 254f;
            this.xrTable5.LocationFloat = new PointFloat(2083.974f, 13.22925f);
            this.xrTable5.Name = "xrTable5";
            XRTableRow[] rowArray3 = new XRTableRow[] { this.xrTableRow7 };
            this.xrTable5.Rows.AddRange(rowArray3);
            this.xrTable5.SizeF = new SizeF(590.156f, 58.88384f);
            this.xrTable5.StylePriority.UseBorders = false;
            this.xrTable5.StylePriority.UseBorderWidth = false;
            XRTableCell[] cellArray3 = new XRTableCell[] { this.xrTableCell11 };
            this.xrTableRow7.Cells.AddRange(cellArray3);
            this.xrTableRow7.Dpi = 254f;
            this.xrTableRow7.Name = "xrTableRow7";
            this.xrTableRow7.Weight = 0.76022880797918213;
            this.xrTableCell11.BorderWidth = 1f;
            this.xrTableCell11.Dpi = 254f;
            this.xrTableCell11.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.xrTableCell11.Multiline = true;
            this.xrTableCell11.Name = "xrTableCell11";
            this.xrTableCell11.Padding = new PaddingInfo(5, 0, 10, 0, 254f);
            this.xrTableCell11.StylePriority.UseBorderWidth = false;
            this.xrTableCell11.StylePriority.UseFont = false;
            this.xrTableCell11.StylePriority.UsePadding = false;
            this.xrTableCell11.Text = "Yetkili Kişi: ";
            this.xrTableCell11.Weight = 3.0;
            this.xrLabel1.Dpi = 254f;
            this.xrLabel1.Font = new Font("Calibri", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.xrLabel1.LocationFloat = new PointFloat(381f, 429.1078f);
            this.xrLabel1.Multiline = true;
            this.xrLabel1.Name = "xrLabel1";
            this.xrLabel1.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrLabel1.SizeF = new SizeF(1921.478f, 98.10751f);
            this.xrLabel1.StylePriority.UseFont = false;
            this.xrLabel1.StylePriority.UsePadding = false;
            this.xrLabel1.StylePriority.UseTextAlignment = false;
            //this.xrLabel1.Text = manager.GetString("xrLabel1.Text");
            this.xrLabel1.TextAlignment = TextAlignment.TopCenter;
            this.xrLine3.Dpi = 254f;
            this.xrLine3.LineWidth = 4;
            this.xrLine3.LocationFloat = new PointFloat(0.004179711f, 381.1496f);
            this.xrLine3.Name = "xrLine3";
            this.xrLine3.SizeF = new SizeF(2754.057f, 13.22916f);
            this.xrTable2.Borders = BorderSide.All;
            this.xrTable2.BorderWidth = 3f;
            this.xrTable2.Dpi = 254f;
            this.xrTable2.LocationFloat = new PointFloat(2083.974f, 72.11309f);
            this.xrTable2.Name = "xrTable2";
            XRTableRow[] rowArray4 = new XRTableRow[] { this.xrTableRow2 };
            this.xrTable2.Rows.AddRange(rowArray4);
            this.xrTable2.SizeF = new SizeF(590.156f, 292.0363f);
            this.xrTable2.StylePriority.UseBorders = false;
            this.xrTable2.StylePriority.UseBorderWidth = false;
            XRTableCell[] cellArray4 = new XRTableCell[] { this.xrOnay };
            this.xrTableRow2.Cells.AddRange(cellArray4);
            this.xrTableRow2.Dpi = 254f;
            this.xrTableRow2.Name = "xrTableRow2";
            this.xrTableRow2.Weight = 0.76022880797918213;
            this.xrOnay.BorderWidth = 1f;
            this.xrOnay.Dpi = 254f;
            this.xrOnay.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.xrOnay.Multiline = true;
            this.xrOnay.Name = "xrOnay";
            this.xrOnay.Padding = new PaddingInfo(5, 0, 10, 0, 254f);
            this.xrOnay.StylePriority.UseBorderWidth = false;
            this.xrOnay.StylePriority.UseFont = false;
            this.xrOnay.StylePriority.UsePadding = false;
            this.xrOnay.StylePriority.UseTextAlignment = false;
            this.xrOnay.Text = "Okudum, Kabul Etiim, Siparişimizdir.\r\nKaşe ve Yetkili kişi İmzası";
            this.xrOnay.TextAlignment = TextAlignment.BottomRight;
            this.xrOnay.Weight = 3.0;
            this.xrSozlesmeKosullari.Dpi = 254f;
            this.xrSozlesmeKosullari.Font = new Font("Calibri", 8f);
            this.xrSozlesmeKosullari.LocationFloat = new PointFloat(0f, 43.89517f);
            this.xrSozlesmeKosullari.Multiline = true;
            this.xrSozlesmeKosullari.Name = "xrSozlesmeKosullari";
            this.xrSozlesmeKosullari.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrSozlesmeKosullari.SizeF = new SizeF(2055.813f, 262.0461f);
            this.xrSozlesmeKosullari.StylePriority.UseFont = false;
            this.xrSozlesmeKosullari.StylePriority.UsePadding = false;
            this.xrSozlesmeKosullari.StylePriority.UseTextAlignment = false;
            this.xrSozlesmeKosullari.Text = "Ge\x00e7erlilik S\x00fcresi\r\nGe\x00e7erlilik S\x00fcresi";
            this.xrSozlesmeKosullari.TextAlignment = TextAlignment.TopLeft;
            this.xrSozlesmeBaslik.Dpi = 254f;
            this.xrSozlesmeBaslik.Font = new Font("Calibri", 8f, FontStyle.Underline | FontStyle.Bold);
            this.xrSozlesmeBaslik.LocationFloat = new PointFloat(0.004158338f, 0f);
            this.xrSozlesmeBaslik.Multiline = true;
            this.xrSozlesmeBaslik.Name = "xrSozlesmeBaslik";
            this.xrSozlesmeBaslik.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrSozlesmeBaslik.SizeF = new SizeF(1750f, 43.89514f);
            this.xrSozlesmeBaslik.StylePriority.UseFont = false;
            this.xrSozlesmeBaslik.StylePriority.UsePadding = false;
            this.xrSozlesmeBaslik.StylePriority.UseTextAlignment = false;
            this.xrSozlesmeBaslik.Text = "SATIŞ S\x00d6ZLEŞMESİ KOŞULLARI";
            this.xrSozlesmeBaslik.TextAlignment = TextAlignment.TopLeft;
            XRControl[] controlArray4 = new XRControl[] {
                this.lblTalepNo, this.xrLabel41, this._lblTalepNo, this.lblTelefon_, this.lblTarih_, this.lblGonderen_, this.lblMail_, this.xrLabel18, this.xrLabel15, this.xrLabel16, this.xrLabel17, this._lblTelefon_, this._lblTarih, this._lblGonderen, this._lblEmail_, this.lblFax,
                this.lblMail, this.lblTeklifNo, this.lblIlgiliKisi, this.lblAlici, this.lblTelefon, this.xrLabel14, this.xrLabel13, this.xrLabel12, this.xrLabel11, this.xrLabel10, this.xrLabel9, this._lblFax, this._lblMail, this._lblTelefon, this._lblIlgiliKisi, this._lblAlici,
                this._lblTeklifNo, this.xrGecerlilikSuresi, this.xrLabel30, this.xrGecerlilikSuresi_
            };
            this.GroupHeader1.Controls.AddRange(controlArray4);
            this.GroupHeader1.Dpi = 254f;
            this.GroupHeader1.HeightF = 172.8668f;
            this.GroupHeader1.Name = "GroupHeader1";
            this.GroupHeader1.StylePriority.UseTextAlignment = false;
            this.GroupHeader1.TextAlignment = TextAlignment.TopLeft;
            this.lblTalepNo.Dpi = 254f;
            this.lblTalepNo.Font = new Font("Calibri", 9f);
            this.lblTalepNo.LocationFloat = new PointFloat(1473.782f, 92.63334f);
            this.lblTalepNo.Name = "lblTalepNo";
            this.lblTalepNo.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblTalepNo.SizeF = new SizeF(489.0488f, 39.41669f);
            this.lblTalepNo.StylePriority.UseFont = false;
            this.lblTalepNo.StylePriority.UsePadding = false;
            this.xrLabel41.Dpi = 254f;
            this.xrLabel41.Font = new Font("Calibri", 9f);
            this.xrLabel41.LocationFloat = new PointFloat(1449.969f, 92.63332f);
            this.xrLabel41.Name = "xrLabel41";
            this.xrLabel41.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel41.SizeF = new SizeF(23.81247f, 39.41672f);
            this.xrLabel41.StylePriority.UseFont = false;
            this.xrLabel41.Text = ":";
            this._lblTalepNo.Dpi = 254f;
            this._lblTalepNo.Font = new Font("Calibri", 9f);
            this._lblTalepNo.LocationFloat = new PointFloat(1231.156f, 92.63332f);
            this._lblTalepNo.Name = "_lblTalepNo";
            this._lblTalepNo.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblTalepNo.SizeF = new SizeF(218.8127f, 39.41673f);
            this._lblTalepNo.StylePriority.UseFont = false;
            this._lblTalepNo.Text = "Talep No";
            this.lblTelefon_.Dpi = 254f;
            this.lblTelefon_.Font = new Font("Calibri", 9f);
            this.lblTelefon_.LocationFloat = new PointFloat(2161.269f, 133.4501f);
            this.lblTelefon_.Name = "lblTelefon_";
            this.lblTelefon_.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblTelefon_.SizeF = new SizeF(452.7495f, 39.41667f);
            this.lblTelefon_.StylePriority.UseFont = false;
            this.lblTelefon_.StylePriority.UsePadding = false;
            this.lblTelefon_.StylePriority.UseTextAlignment = false;
            this.lblTelefon_.TextAlignment = TextAlignment.TopLeft;
            this.lblTarih_.Dpi = 254f;
            this.lblTarih_.Font = new Font("Calibri", 9f);
            this.lblTarih_.LocationFloat = new PointFloat(2161.269f, 11.00001f);
            this.lblTarih_.Name = "lblTarih_";
            this.lblTarih_.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblTarih_.SizeF = new SizeF(452.7495f, 39.41666f);
            this.lblTarih_.StylePriority.UseFont = false;
            this.lblTarih_.StylePriority.UsePadding = false;
            this.lblTarih_.StylePriority.UseTextAlignment = false;
            this.lblTarih_.TextAlignment = TextAlignment.TopLeft;
            this.lblGonderen_.Dpi = 254f;
            this.lblGonderen_.Font = new Font("Calibri", 9f);
            this.lblGonderen_.LocationFloat = new PointFloat(2161.269f, 51.81666f);
            this.lblGonderen_.Name = "lblGonderen_";
            this.lblGonderen_.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblGonderen_.SizeF = new SizeF(452.7495f, 39.41668f);
            this.lblGonderen_.StylePriority.UseFont = false;
            this.lblGonderen_.StylePriority.UsePadding = false;
            this.lblGonderen_.StylePriority.UseTextAlignment = false;
            this.lblGonderen_.TextAlignment = TextAlignment.TopLeft;
            this.lblMail_.Dpi = 254f;
            this.lblMail_.Font = new Font("Calibri", 9f);
            this.lblMail_.LocationFloat = new PointFloat(2161.269f, 92.63334f);
            this.lblMail_.Name = "lblMail_";
            this.lblMail_.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblMail_.SizeF = new SizeF(452.7495f, 39.41669f);
            this.lblMail_.StylePriority.UseFont = false;
            this.lblMail_.StylePriority.UsePadding = false;
            this.lblMail_.StylePriority.UseTextAlignment = false;
            this.lblMail_.TextAlignment = TextAlignment.TopLeft;
            this.xrLabel18.Dpi = 254f;
            this.xrLabel18.Font = new Font("Calibri", 9f);
            this.xrLabel18.LocationFloat = new PointFloat(2137.456f, 133.4501f);
            this.xrLabel18.Name = "xrLabel18";
            this.xrLabel18.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel18.SizeF = new SizeF(23.81247f, 39.41667f);
            this.xrLabel18.StylePriority.UseFont = false;
            this.xrLabel18.Text = ":";
            this.xrLabel15.Dpi = 254f;
            this.xrLabel15.Font = new Font("Calibri", 9f);
            this.xrLabel15.LocationFloat = new PointFloat(2137.456f, 11.00001f);
            this.xrLabel15.Name = "xrLabel15";
            this.xrLabel15.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel15.SizeF = new SizeF(23.81247f, 39.41666f);
            this.xrLabel15.StylePriority.UseFont = false;
            this.xrLabel15.Text = ":";
            this.xrLabel16.Dpi = 254f;
            this.xrLabel16.Font = new Font("Calibri", 9f);
            this.xrLabel16.LocationFloat = new PointFloat(2137.456f, 51.81667f);
            this.xrLabel16.Name = "xrLabel16";
            this.xrLabel16.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel16.SizeF = new SizeF(23.81247f, 39.41666f);
            this.xrLabel16.StylePriority.UseFont = false;
            this.xrLabel16.Text = ":";
            this.xrLabel17.Dpi = 254f;
            this.xrLabel17.Font = new Font("Calibri", 9f);
            this.xrLabel17.LocationFloat = new PointFloat(2137.456f, 92.63334f);
            this.xrLabel17.Name = "xrLabel17";
            this.xrLabel17.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel17.SizeF = new SizeF(23.81247f, 39.41669f);
            this.xrLabel17.StylePriority.UseFont = false;
            this.xrLabel17.Text = ":";
            this._lblTelefon_.Dpi = 254f;
            this._lblTelefon_.Font = new Font("Calibri", 9f);
            this._lblTelefon_.LocationFloat = new PointFloat(1962.831f, 133.4501f);
            this._lblTelefon_.Name = "_lblTelefon_";
            this._lblTelefon_.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblTelefon_.SizeF = new SizeF(174.625f, 39.41667f);
            this._lblTelefon_.StylePriority.UseFont = false;
            this._lblTelefon_.StylePriority.UseTextAlignment = false;
            this._lblTelefon_.Text = "Telefon";
            this._lblTelefon_.TextAlignment = TextAlignment.TopLeft;
            this._lblTarih.Dpi = 254f;
            this._lblTarih.Font = new Font("Calibri", 9f);
            this._lblTarih.LocationFloat = new PointFloat(1962.831f, 11.00001f);
            this._lblTarih.Name = "_lblTarih";
            this._lblTarih.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblTarih.SizeF = new SizeF(174.625f, 39.41666f);
            this._lblTarih.StylePriority.UseFont = false;
            this._lblTarih.StylePriority.UseTextAlignment = false;
            this._lblTarih.Text = "Tarih";
            this._lblTarih.TextAlignment = TextAlignment.TopLeft;
            this._lblGonderen.Dpi = 254f;
            this._lblGonderen.Font = new Font("Calibri", 9f);
            this._lblGonderen.LocationFloat = new PointFloat(1962.831f, 51.81667f);
            this._lblGonderen.Name = "_lblGonderen";
            this._lblGonderen.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblGonderen.SizeF = new SizeF(174.625f, 39.41666f);
            this._lblGonderen.StylePriority.UseFont = false;
            this._lblGonderen.StylePriority.UseTextAlignment = false;
            this._lblGonderen.Text = "G\x00f6nderen";
            this._lblGonderen.TextAlignment = TextAlignment.TopLeft;
            this._lblEmail_.Dpi = 254f;
            this._lblEmail_.Font = new Font("Calibri", 9f);
            this._lblEmail_.LocationFloat = new PointFloat(1962.831f, 92.63334f);
            this._lblEmail_.Name = "_lblEmail_";
            this._lblEmail_.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblEmail_.SizeF = new SizeF(174.625f, 39.41669f);
            this._lblEmail_.StylePriority.UseFont = false;
            this._lblEmail_.StylePriority.UseTextAlignment = false;
            this._lblEmail_.Text = "Email";
            this._lblEmail_.TextAlignment = TextAlignment.TopLeft;
            this.lblFax.Dpi = 254f;
            this.lblFax.Font = new Font("Calibri", 9f);
            this.lblFax.LocationFloat = new PointFloat(1473.782f, 51.81664f);
            this.lblFax.Name = "lblFax";
            this.lblFax.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblFax.SizeF = new SizeF(489.0493f, 39.41673f);
            this.lblFax.StylePriority.UseFont = false;
            this.lblFax.StylePriority.UsePadding = false;
            this.lblMail.Dpi = 254f;
            this.lblMail.Font = new Font("Calibri", 9f);
            this.lblMail.LocationFloat = new PointFloat(1473.782f, 11.00002f);
            this.lblMail.Name = "lblMail";
            this.lblMail.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblMail.SizeF = new SizeF(489.0493f, 39.41663f);
            this.lblMail.StylePriority.UseFont = false;
            this.lblMail.StylePriority.UsePadding = false;
            this.lblTeklifNo.Dpi = 254f;
            this.lblTeklifNo.Font = new Font("Calibri", 9f);
            this.lblTeklifNo.LocationFloat = new PointFloat(198.4374f, 11.00001f);
            this.lblTeklifNo.Name = "lblTeklifNo";
            this.lblTeklifNo.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblTeklifNo.SizeF = new SizeF(998.7015f, 39.41666f);
            this.lblTeklifNo.StylePriority.UseFont = false;
            this.lblTeklifNo.StylePriority.UsePadding = false;
            this.lblIlgiliKisi.Dpi = 254f;
            this.lblIlgiliKisi.Font = new Font("Calibri", 9f);
            this.lblIlgiliKisi.LocationFloat = new PointFloat(198.4374f, 92.63334f);
            this.lblIlgiliKisi.Name = "lblIlgiliKisi";
            this.lblIlgiliKisi.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblIlgiliKisi.SizeF = new SizeF(998.7015f, 39.41669f);
            this.lblIlgiliKisi.StylePriority.UseFont = false;
            this.lblIlgiliKisi.StylePriority.UsePadding = false;
            this.lblAlici.Dpi = 254f;
            this.lblAlici.Font = new Font("Calibri", 9f);
            this.lblAlici.LocationFloat = new PointFloat(198.4374f, 51.81667f);
            this.lblAlici.Name = "lblAlici";
            this.lblAlici.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblAlici.SizeF = new SizeF(998.7015f, 39.41666f);
            this.lblAlici.StylePriority.UseFont = false;
            this.lblAlici.StylePriority.UsePadding = false;
            this.lblTelefon.Dpi = 254f;
            this.lblTelefon.Font = new Font("Calibri", 9f);
            this.lblTelefon.LocationFloat = new PointFloat(198.4374f, 133.4501f);
            this.lblTelefon.Name = "lblTelefon";
            this.lblTelefon.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.lblTelefon.SizeF = new SizeF(998.7015f, 39.41669f);
            this.lblTelefon.StylePriority.UseFont = false;
            this.lblTelefon.StylePriority.UsePadding = false;
            this.xrLabel14.Dpi = 254f;
            this.xrLabel14.Font = new Font("Calibri", 9f);
            this.xrLabel14.LocationFloat = new PointFloat(1449.969f, 51.81664f);
            this.xrLabel14.Name = "xrLabel14";
            this.xrLabel14.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel14.SizeF = new SizeF(23.81247f, 39.41672f);
            this.xrLabel14.StylePriority.UseFont = false;
            this.xrLabel14.Text = ":";
            this.xrLabel13.Dpi = 254f;
            this.xrLabel13.Font = new Font("Calibri", 9f);
            this.xrLabel13.LocationFloat = new PointFloat(1449.969f, 11.00002f);
            this.xrLabel13.Name = "xrLabel13";
            this.xrLabel13.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel13.SizeF = new SizeF(23.81247f, 39.41663f);
            this.xrLabel13.StylePriority.UseFont = false;
            this.xrLabel13.Text = ":";
            this.xrLabel12.Dpi = 254f;
            this.xrLabel12.Font = new Font("Calibri", 9f);
            this.xrLabel12.LocationFloat = new PointFloat(174.6249f, 133.4501f);
            this.xrLabel12.Name = "xrLabel12";
            this.xrLabel12.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel12.SizeF = new SizeF(23.81247f, 39.41667f);
            this.xrLabel12.StylePriority.UseFont = false;
            this.xrLabel12.Text = ":";
            this.xrLabel11.Dpi = 254f;
            this.xrLabel11.Font = new Font("Calibri", 9f);
            this.xrLabel11.LocationFloat = new PointFloat(174.6249f, 92.63334f);
            this.xrLabel11.Name = "xrLabel11";
            this.xrLabel11.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel11.SizeF = new SizeF(23.81247f, 39.41669f);
            this.xrLabel11.StylePriority.UseFont = false;
            this.xrLabel11.Text = ":";
            this.xrLabel10.Dpi = 254f;
            this.xrLabel10.Font = new Font("Calibri", 9f);
            this.xrLabel10.LocationFloat = new PointFloat(174.6249f, 51.81667f);
            this.xrLabel10.Name = "xrLabel10";
            this.xrLabel10.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel10.SizeF = new SizeF(23.81247f, 39.41666f);
            this.xrLabel10.StylePriority.UseFont = false;
            this.xrLabel10.Text = ":";
            this.xrLabel9.Dpi = 254f;
            this.xrLabel9.Font = new Font("Calibri", 9f);
            this.xrLabel9.LocationFloat = new PointFloat(174.6249f, 11.00001f);
            this.xrLabel9.Name = "xrLabel9";
            this.xrLabel9.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel9.SizeF = new SizeF(23.81247f, 39.41666f);
            this.xrLabel9.StylePriority.UseFont = false;
            this.xrLabel9.Text = ":";
            this._lblFax.Dpi = 254f;
            this._lblFax.Font = new Font("Calibri", 9f);
            this._lblFax.LocationFloat = new PointFloat(1231.156f, 51.81664f);
            this._lblFax.Name = "_lblFax";
            this._lblFax.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblFax.SizeF = new SizeF(218.8127f, 39.41673f);
            this._lblFax.StylePriority.UseFont = false;
            this._lblFax.Text = "Fax";
            this._lblMail.Dpi = 254f;
            this._lblMail.Font = new Font("Calibri", 9f);
            this._lblMail.LocationFloat = new PointFloat(1231.156f, 11.00002f);
            this._lblMail.Name = "_lblMail";
            this._lblMail.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblMail.SizeF = new SizeF(218.8127f, 39.41663f);
            this._lblMail.StylePriority.UseFont = false;
            this._lblMail.Text = "Email";
            this._lblTelefon.Dpi = 254f;
            this._lblTelefon.Font = new Font("Calibri", 9f);
            this._lblTelefon.LocationFloat = new PointFloat(0f, 133.4501f);
            this._lblTelefon.Name = "_lblTelefon";
            this._lblTelefon.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblTelefon.SizeF = new SizeF(174.625f, 39.41667f);
            this._lblTelefon.StylePriority.UseFont = false;
            this._lblTelefon.Text = "Telefon";
            this._lblIlgiliKisi.Dpi = 254f;
            this._lblIlgiliKisi.Font = new Font("Calibri", 9f);
            this._lblIlgiliKisi.LocationFloat = new PointFloat(0f, 92.63334f);
            this._lblIlgiliKisi.Name = "_lblIlgiliKisi";
            this._lblIlgiliKisi.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblIlgiliKisi.SizeF = new SizeF(174.625f, 39.41669f);
            this._lblIlgiliKisi.StylePriority.UseFont = false;
            this._lblIlgiliKisi.Text = "İlgili Kişi";
            this._lblAlici.Dpi = 254f;
            this._lblAlici.Font = new Font("Calibri", 9f);
            this._lblAlici.LocationFloat = new PointFloat(0f, 51.81667f);
            this._lblAlici.Name = "_lblAlici";
            this._lblAlici.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblAlici.SizeF = new SizeF(174.625f, 39.41666f);
            this._lblAlici.StylePriority.UseFont = false;
            this._lblAlici.Text = "Alıcı";
            this._lblTeklifNo.Dpi = 254f;
            this._lblTeklifNo.Font = new Font("Calibri", 9f);
            this._lblTeklifNo.LocationFloat = new PointFloat(0f, 11.00001f);
            this._lblTeklifNo.Name = "_lblTeklifNo";
            this._lblTeklifNo.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this._lblTeklifNo.SizeF = new SizeF(174.625f, 39.41666f);
            this._lblTeklifNo.StylePriority.UseFont = false;
            this._lblTeklifNo.Text = "Teklif No";
            this.xrGecerlilikSuresi.Dpi = 254f;
            this.xrGecerlilikSuresi.Font = new Font("Calibri", 9f);
            this.xrGecerlilikSuresi.LocationFloat = new PointFloat(1231.156f, 135.5458f);
            this.xrGecerlilikSuresi.Name = "xrGecerlilikSuresi";
            this.xrGecerlilikSuresi.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrGecerlilikSuresi.SizeF = new SizeF(218.8127f, 37.32103f);
            this.xrGecerlilikSuresi.StylePriority.UseFont = false;
            this.xrGecerlilikSuresi.StylePriority.UseTextAlignment = false;
            this.xrGecerlilikSuresi.Text = "Ge\x00e7erlilik S\x00fcresi";
            this.xrGecerlilikSuresi.TextAlignment = TextAlignment.MiddleLeft;
            this.xrLabel30.Dpi = 254f;
            this.xrLabel30.Font = new Font("Calibri", 9f);
            this.xrLabel30.LocationFloat = new PointFloat(1449.969f, 135.5458f);
            this.xrLabel30.Name = "xrLabel30";
            this.xrLabel30.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel30.SizeF = new SizeF(23.8125f, 37.32103f);
            this.xrLabel30.StylePriority.UseFont = false;
            this.xrLabel30.StylePriority.UseTextAlignment = false;
            this.xrLabel30.Text = ":";
            this.xrLabel30.TextAlignment = TextAlignment.MiddleLeft;
            this.xrGecerlilikSuresi_.Dpi = 254f;
            this.xrGecerlilikSuresi_.Font = new Font("Calibri", 9f);
            this.xrGecerlilikSuresi_.LocationFloat = new PointFloat(1473.782f, 135.5458f);
            this.xrGecerlilikSuresi_.Name = "xrGecerlilikSuresi_";
            this.xrGecerlilikSuresi_.Padding = new PaddingInfo(15, 5, 0, 0, 254f);
            this.xrGecerlilikSuresi_.SizeF = new SizeF(276.222f, 37.32103f);
            this.xrGecerlilikSuresi_.StylePriority.UseFont = false;
            this.xrGecerlilikSuresi_.StylePriority.UsePadding = false;
            this.xrGecerlilikSuresi_.StylePriority.UseTextAlignment = false;
            this.xrGecerlilikSuresi_.Text = "Ge\x00e7erlilik S\x00fcresi";
            this.xrGecerlilikSuresi_.TextAlignment = TextAlignment.MiddleLeft;
            XRControl[] controlArray5 = new XRControl[] {
                this.lblNot, this.lblNotIkiNokta, this.lblNot_, this.xrIbanNo, this.xrLabel4, this.xrLabel3, this.xrKurAdi, this.xrLabel25, this.xrHesapNo, this.xrToplamAgirlik_, this.xrLabel26, this.xrToplamAgirlik, this.xrTable3, this.xrLabel37, this.xrOdemeSekli_, this.xrLabel32,
                this.xrOdemeSekli
            };
            this.ReportFooter.Controls.AddRange(controlArray5);
            this.ReportFooter.Dpi = 254f;
            this.ReportFooter.HeightF = 368.923f;
            this.ReportFooter.Name = "ReportFooter";
            this.lblNot.Dpi = 254f;
            this.lblNot.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.lblNot.LocationFloat = new PointFloat(278.2092f, 17f);
            this.lblNot.Name = "lblNot";
            this.lblNot.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.lblNot.SizeF = new SizeF(1625.395f, 38.43743f);
            this.lblNot.StylePriority.UseFont = false;
            this.lblNot.StylePriority.UseTextAlignment = false;
            this.lblNot.Text = "--------";
            this.lblNot.TextAlignment = TextAlignment.MiddleLeft;
            this.lblNotIkiNokta.Dpi = 254f;
            this.lblNotIkiNokta.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.lblNotIkiNokta.LocationFloat = new PointFloat(234.692f, 17f);
            this.lblNotIkiNokta.Name = "lblNotIkiNokta";
            this.lblNotIkiNokta.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.lblNotIkiNokta.SizeF = new SizeF(16.51736f, 38.43743f);
            this.lblNotIkiNokta.StylePriority.UseFont = false;
            this.lblNotIkiNokta.StylePriority.UseTextAlignment = false;
            this.lblNotIkiNokta.Text = ":";
            this.lblNotIkiNokta.TextAlignment = TextAlignment.MiddleLeft;
            this.lblNot_.Dpi = 254f;
            this.lblNot_.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.lblNot_.LocationFloat = new PointFloat(0.004158338f, 17f);
            this.lblNot_.Name = "lblNot_";
            this.lblNot_.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.lblNot_.SizeF = new SizeF(234.6877f, 38.43743f);
            this.lblNot_.StylePriority.UseFont = false;
            this.lblNot_.StylePriority.UseTextAlignment = false;
            this.lblNot_.Text = "Not";
            this.lblNot_.TextAlignment = TextAlignment.MiddleLeft;
            this.xrIbanNo.Dpi = 254f;
            this.xrIbanNo.Font = new Font("Calibri", 8f);
            this.xrIbanNo.LocationFloat = new PointFloat(999.0333f, 197.2701f);
            this.xrIbanNo.Multiline = true;
            this.xrIbanNo.Name = "xrIbanNo";
            this.xrIbanNo.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrIbanNo.SizeF = new SizeF(537.1f, 40f);
            this.xrIbanNo.StylePriority.UseFont = false;
            this.xrIbanNo.StylePriority.UsePadding = false;
            this.xrIbanNo.StylePriority.UseTextAlignment = false;
            this.xrIbanNo.TextAlignment = TextAlignment.TopLeft;
            this.xrLabel4.Dpi = 254f;
            this.xrLabel4.Font = new Font("Calibri", 8f);
            this.xrLabel4.LocationFloat = new PointFloat(999.0333f, 157.27f);
            this.xrLabel4.Multiline = true;
            this.xrLabel4.Name = "xrLabel4";
            this.xrLabel4.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrLabel4.SizeF = new SizeF(537.1f, 40f);
            this.xrLabel4.StylePriority.UseFont = false;
            this.xrLabel4.StylePriority.UsePadding = false;
            this.xrLabel4.StylePriority.UseTextAlignment = false;
            this.xrLabel4.Text = "TR31 0006 4000 0011 1880 3662 76";
            this.xrLabel4.TextAlignment = TextAlignment.TopLeft;
            this.xrLabel3.Dpi = 254f;
            this.xrLabel3.Font = new Font("Calibri", 8f);
            this.xrLabel3.LocationFloat = new PointFloat(0f, 157.2701f);
            this.xrLabel3.Multiline = true;
            this.xrLabel3.Name = "xrLabel3";
            this.xrLabel3.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrLabel3.SizeF = new SizeF(604.35f, 40f);
            this.xrLabel3.StylePriority.UseFont = false;
            this.xrLabel3.StylePriority.UsePadding = false;
            this.xrLabel3.StylePriority.UseTextAlignment = false;
            this.xrLabel3.Text = "T\x00dcRKİYE İŞ BANKASI PERPA ŞUBESİ";
            this.xrLabel3.TextAlignment = TextAlignment.TopLeft;
            this.xrKurAdi.Dpi = 254f;
            this.xrKurAdi.Font = new Font("Calibri", 8f);
            this.xrKurAdi.LocationFloat = new PointFloat(665.3125f, 197.2701f);
            this.xrKurAdi.Multiline = true;
            this.xrKurAdi.Name = "xrKurAdi";
            this.xrKurAdi.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrKurAdi.SizeF = new SizeF(333.72f, 40f);
            this.xrKurAdi.StylePriority.UseFont = false;
            this.xrKurAdi.StylePriority.UsePadding = false;
            this.xrKurAdi.StylePriority.UseTextAlignment = false;
            this.xrKurAdi.TextAlignment = TextAlignment.TopLeft;
            this.xrLabel25.Dpi = 254f;
            this.xrLabel25.Font = new Font("Calibri", 8f);
            this.xrLabel25.LocationFloat = new PointFloat(665.3124f, 157.2701f);
            this.xrLabel25.Multiline = true;
            this.xrLabel25.Name = "xrLabel25";
            this.xrLabel25.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrLabel25.SizeF = new SizeF(333.72f, 40f);
            this.xrLabel25.StylePriority.UseFont = false;
            this.xrLabel25.StylePriority.UsePadding = false;
            this.xrLabel25.StylePriority.UseTextAlignment = false;
            this.xrLabel25.Text = "TL HESABI";
            this.xrLabel25.TextAlignment = TextAlignment.TopLeft;
            this.xrHesapNo.Dpi = 254f;
            this.xrHesapNo.Font = new Font("Calibri", 8f);
            this.xrHesapNo.LocationFloat = new PointFloat(0.004150391f, 197.2701f);
            this.xrHesapNo.Multiline = true;
            this.xrHesapNo.Name = "xrHesapNo";
            this.xrHesapNo.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrHesapNo.SizeF = new SizeF(604.35f, 40f);
            this.xrHesapNo.StylePriority.UseFont = false;
            this.xrHesapNo.StylePriority.UsePadding = false;
            this.xrHesapNo.StylePriority.UseTextAlignment = false;
            this.xrHesapNo.Text = "T\x00dcRKİYE İŞ BANKASI PERPA ŞUBESİ";
            this.xrHesapNo.TextAlignment = TextAlignment.TopLeft;
            XRBinding[] bindingArray9 = new XRBinding[] { new XRBinding("Text", this.dstQuotation1, "dtQuotation.SatirAgirligi") };
            //this.xrToplamAgirlik_.DataBindings.AddRange(bindingArray9);
            this.xrToplamAgirlik_.Dpi = 254f;
            this.xrToplamAgirlik_.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.xrToplamAgirlik_.LocationFloat = new PointFloat(943.5172f, 61.56243f);
            this.xrToplamAgirlik_.Name = "xrToplamAgirlik_";
            this.xrToplamAgirlik_.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrToplamAgirlik_.SizeF = new SizeF(319.8213f, 39.8125f);
            this.xrToplamAgirlik_.StylePriority.UseFont = false;
            this.xrToplamAgirlik_.StylePriority.UseTextAlignment = false;
            summary.FormatString = "{0:F3}";
            summary.Running = SummaryRunning.Report;
            this.xrToplamAgirlik_.Summary = summary;
            this.xrToplamAgirlik_.Text = "xrToplamAgirlik_";
            this.xrToplamAgirlik_.TextAlignment = TextAlignment.MiddleLeft;
            this.xrLabel26.Dpi = 254f;
            this.xrLabel26.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.xrLabel26.LocationFloat = new PointFloat(900.0005f, 61.56243f);
            this.xrLabel26.Name = "xrLabel26";
            this.xrLabel26.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel26.SizeF = new SizeF(16.51733f, 39.8125f);
            this.xrLabel26.StylePriority.UseFont = false;
            this.xrLabel26.StylePriority.UseTextAlignment = false;
            this.xrLabel26.Text = ":";
            this.xrLabel26.TextAlignment = TextAlignment.MiddleLeft;
            this.xrToplamAgirlik.Dpi = 254f;
            this.xrToplamAgirlik.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.xrToplamAgirlik.LocationFloat = new PointFloat(665.3124f, 61.56243f);
            this.xrToplamAgirlik.Name = "xrToplamAgirlik";
            this.xrToplamAgirlik.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrToplamAgirlik.SizeF = new SizeF(234.6876f, 39.81249f);
            this.xrToplamAgirlik.StylePriority.UseFont = false;
            this.xrToplamAgirlik.StylePriority.UseTextAlignment = false;
            this.xrToplamAgirlik.Text = "Toplam Ağırlık";
            this.xrToplamAgirlik.TextAlignment = TextAlignment.MiddleLeft;
            this.xrTable3.Borders = BorderSide.All;
            this.xrTable3.BorderWidth = 1f;
            this.xrTable3.Dpi = 254f;
            this.xrTable3.Font = new Font("Calibri", 8.5f, FontStyle.Bold);
            this.xrTable3.LocationFloat = new PointFloat(2083.974f, 0f);
            this.xrTable3.Name = "xrTable3";
            this.xrTable3.Padding = new PaddingInfo(5, 0, 0, 0, 254f);
            XRTableRow[] rowArray5 = new XRTableRow[] { this.xrTableRow11, this.xrTableRow12, this.xrTableRow8, this.xrTableRow9, this.xrTableRow3, this.xrTableRow4, this.xrTableRow5 };
            this.xrTable3.Rows.AddRange(rowArray5);
            this.xrTable3.SizeF = new SizeF(458.1714f, 368.923f);
            this.xrTable3.StylePriority.UseBorders = false;
            this.xrTable3.StylePriority.UseBorderWidth = false;
            this.xrTable3.StylePriority.UseFont = false;
            this.xrTable3.StylePriority.UsePadding = false;
            this.xrTable3.StylePriority.UseTextAlignment = false;
            this.xrTable3.TextAlignment = TextAlignment.MiddleLeft;
            XRTableCell[] cellArray5 = new XRTableCell[] { this.xrTableCell22, this.lblToplam, this.xrTableCell27 };
            this.xrTableRow11.Cells.AddRange(cellArray5);
            this.xrTableRow11.Dpi = 254f;
            this.xrTableRow11.Name = "xrTableRow11";
            this.xrTableRow11.Weight = 1.0;
            this.xrTableCell22.Dpi = 254f;
            this.xrTableCell22.Font = new Font("Calibri", 9f, FontStyle.Bold);
            this.xrTableCell22.Name = "xrTableCell22";
            this.xrTableCell22.StylePriority.UseFont = false;
            this.xrTableCell22.Text = "TOPLAM";
            this.xrTableCell22.Weight = 1.4307129300313002;
            this.lblToplam.Borders = BorderSide.Bottom | BorderSide.Top | BorderSide.Left;
            this.lblToplam.Dpi = 254f;
            this.lblToplam.Font = new Font("Calibri", 9f);
            this.lblToplam.Name = "lblToplam";
            this.lblToplam.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.lblToplam.StylePriority.UseBorders = false;
            this.lblToplam.StylePriority.UseFont = false;
            this.lblToplam.StylePriority.UsePadding = false;
            this.lblToplam.StylePriority.UseTextAlignment = false;
            this.lblToplam.Text = "lblToplam";
            this.lblToplam.TextAlignment = TextAlignment.MiddleRight;
            this.lblToplam.Weight = 1.2622687293972121;
            this.xrTableCell27.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Top;
            XRBinding[] bindingArray10 = new XRBinding[] { new XRBinding("Text", this.dstQuotation1, "dtQuotation.SINGS") };
            //this.xrTableCell27.DataBindings.AddRange(bindingArray10);
            this.xrTableCell27.Dpi = 254f;
            this.xrTableCell27.Font = new Font("Calibri", 9f);
            this.xrTableCell27.Name = "xrTableCell27";
            this.xrTableCell27.StylePriority.UseBorders = false;
            this.xrTableCell27.StylePriority.UseFont = false;
            this.xrTableCell27.Text = "xrTableCell27";
            this.xrTableCell27.Weight = 0.30701834057148786;
            XRTableCell[] cellArray6 = new XRTableCell[] { this.xrTableCell25, this.lblIndirim, this.xrTableCell29 };
            this.xrTableRow12.Cells.AddRange(cellArray6);
            this.xrTableRow12.Dpi = 254f;
            this.xrTableRow12.Name = "xrTableRow12";
            this.xrTableRow12.Weight = 1.0;
            this.xrTableCell25.Dpi = 254f;
            this.xrTableCell25.Font = new Font("Calibri", 9f, FontStyle.Bold);
            this.xrTableCell25.Name = "xrTableCell25";
            this.xrTableCell25.StylePriority.UseFont = false;
            this.xrTableCell25.Text = "INDIRIM";
            this.xrTableCell25.Weight = 1.4307129300313002;
            this.lblIndirim.Borders = BorderSide.Bottom | BorderSide.Top | BorderSide.Left;
            this.lblIndirim.Dpi = 254f;
            this.lblIndirim.Font = new Font("Calibri", 9f);
            this.lblIndirim.Name = "lblIndirim";
            this.lblIndirim.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.lblIndirim.StylePriority.UseBorders = false;
            this.lblIndirim.StylePriority.UseFont = false;
            this.lblIndirim.StylePriority.UsePadding = false;
            this.lblIndirim.StylePriority.UseTextAlignment = false;
            this.lblIndirim.Text = "lblIndirim";
            this.lblIndirim.TextAlignment = TextAlignment.MiddleRight;
            this.lblIndirim.Weight = 1.2622687293972121;
            this.xrTableCell29.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Top;
            XRBinding[] bindingArray11 = new XRBinding[] { new XRBinding("Text", this.dstQuotation1, "dtQuotation.SINGS") };
            //this.xrTableCell29.DataBindings.AddRange(bindingArray11);
            this.xrTableCell29.Dpi = 254f;
            this.xrTableCell29.Font = new Font("Calibri", 9f);
            this.xrTableCell29.Name = "xrTableCell29";
            this.xrTableCell29.StylePriority.UseBorders = false;
            this.xrTableCell29.StylePriority.UseFont = false;
            this.xrTableCell29.Text = "xrTableCell29";
            this.xrTableCell29.Weight = 0.30701834057148786;
            XRTableCell[] cellArray7 = new XRTableCell[] { this.xrTableCell13, this.lblKargoBedeli, this.xrTableCell21 };
            this.xrTableRow8.Cells.AddRange(cellArray7);
            this.xrTableRow8.Dpi = 254f;
            this.xrTableRow8.Name = "xrTableRow8";
            this.xrTableRow8.Weight = 1.0;
            this.xrTableCell13.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrTableCell13.Dpi = 254f;
            this.xrTableCell13.Font = new Font("Calibri", 9f, FontStyle.Bold);
            this.xrTableCell13.Name = "xrTableCell13";
            this.xrTableCell13.StylePriority.UseBorders = false;
            this.xrTableCell13.StylePriority.UseFont = false;
            this.xrTableCell13.Text = "KARGO BEDELİ";
            this.xrTableCell13.Weight = 1.4307129300313002;
            this.lblKargoBedeli.Borders = BorderSide.Bottom | BorderSide.Left;
            this.lblKargoBedeli.Dpi = 254f;
            this.lblKargoBedeli.Font = new Font("Calibri", 9f);
            this.lblKargoBedeli.Name = "lblKargoBedeli";
            this.lblKargoBedeli.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.lblKargoBedeli.StylePriority.UseBorders = false;
            this.lblKargoBedeli.StylePriority.UseFont = false;
            this.lblKargoBedeli.StylePriority.UsePadding = false;
            this.lblKargoBedeli.StylePriority.UseTextAlignment = false;
            this.lblKargoBedeli.Text = "lblKargoBedeli";
            this.lblKargoBedeli.TextAlignment = TextAlignment.MiddleRight;
            this.lblKargoBedeli.Weight = 1.2622687293972121;
            this.xrTableCell21.Borders = BorderSide.Bottom | BorderSide.Right;
            XRBinding[] bindingArray12 = new XRBinding[] { new XRBinding("Text", this.dstQuotation1, "dtQuotation.SINGS") };
            //this.xrTableCell21.DataBindings.AddRange(bindingArray12);
            this.xrTableCell21.Dpi = 254f;
            this.xrTableCell21.Font = new Font("Calibri", 9f);
            this.xrTableCell21.Name = "xrTableCell21";
            this.xrTableCell21.StylePriority.UseBorders = false;
            this.xrTableCell21.StylePriority.UseFont = false;
            this.xrTableCell21.Text = "xrTableCell21";
            this.xrTableCell21.Weight = 0.30701834057148786;
            XRTableCell[] cellArray8 = new XRTableCell[] { this.xrTableCell14, this.lblDeliveryCost, this.xrTableCell23 };
            this.xrTableRow9.Cells.AddRange(cellArray8);
            this.xrTableRow9.Dpi = 254f;
            this.xrTableRow9.Name = "xrTableRow9";
            this.xrTableRow9.Weight = 1.0;
            this.xrTableCell14.Dpi = 254f;
            this.xrTableCell14.Font = new Font("Calibri", 9f, FontStyle.Bold);
            this.xrTableCell14.Name = "xrTableCell14";
            this.xrTableCell14.StylePriority.UseFont = false;
            this.xrTableCell14.Text = "DELIVERY COST";
            this.xrTableCell14.Weight = 1.4307129300313002;
            this.lblDeliveryCost.Borders = BorderSide.Bottom | BorderSide.Top | BorderSide.Left;
            this.lblDeliveryCost.Dpi = 254f;
            this.lblDeliveryCost.Font = new Font("Calibri", 9f);
            this.lblDeliveryCost.Name = "lblDeliveryCost";
            this.lblDeliveryCost.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.lblDeliveryCost.StylePriority.UseBorders = false;
            this.lblDeliveryCost.StylePriority.UseFont = false;
            this.lblDeliveryCost.StylePriority.UsePadding = false;
            this.lblDeliveryCost.StylePriority.UseTextAlignment = false;
            this.lblDeliveryCost.Text = "lblDeliveryCost";
            this.lblDeliveryCost.TextAlignment = TextAlignment.MiddleRight;
            this.lblDeliveryCost.Weight = 1.2622687293972121;
            this.xrTableCell23.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Top;
            XRBinding[] bindingArray13 = new XRBinding[] { new XRBinding("Text", this.dstQuotation1, "dtQuotation.SINGS") };
            //this.xrTableCell23.DataBindings.AddRange(bindingArray13);
            this.xrTableCell23.Dpi = 254f;
            this.xrTableCell23.Font = new Font("Calibri", 9f);
            this.xrTableCell23.Name = "xrTableCell23";
            this.xrTableCell23.StylePriority.UseBorders = false;
            this.xrTableCell23.StylePriority.UseFont = false;
            this.xrTableCell23.Text = "xrTableCell23";
            this.xrTableCell23.Weight = 0.30701834057148786;
            XRTableCell[] cellArray9 = new XRTableCell[] { this.xrNetToplam, this.xrTableCell17, this.xrTableCell15 };
            this.xrTableRow3.Cells.AddRange(cellArray9);
            this.xrTableRow3.Dpi = 254f;
            this.xrTableRow3.Name = "xrTableRow3";
            this.xrTableRow3.Weight = 1.0;
            this.xrNetToplam.Dpi = 254f;
            this.xrNetToplam.Font = new Font("Calibri", 9f, FontStyle.Bold);
            this.xrNetToplam.Name = "xrNetToplam";
            this.xrNetToplam.StylePriority.UseFont = false;
            this.xrNetToplam.Text = "NET TOPLAM";
            this.xrNetToplam.Weight = 1.4307129300313002;
            this.xrTableCell17.Borders = BorderSide.Bottom | BorderSide.Top | BorderSide.Left;
            this.xrTableCell17.Dpi = 254f;
            this.xrTableCell17.Font = new Font("Calibri", 9f);
            this.xrTableCell17.Name = "xrTableCell17";
            this.xrTableCell17.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrTableCell17.StylePriority.UseBorders = false;
            this.xrTableCell17.StylePriority.UseFont = false;
            this.xrTableCell17.StylePriority.UsePadding = false;
            this.xrTableCell17.StylePriority.UseTextAlignment = false;
            summary2.FormatString = "{0:n}";
            this.xrTableCell17.Summary = summary2;
            this.xrTableCell17.Text = "xrTableCell17";
            this.xrTableCell17.TextAlignment = TextAlignment.MiddleRight;
            this.xrTableCell17.Weight = 1.2622687293972121;
            this.xrTableCell15.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Top;
            XRBinding[] bindingArray14 = new XRBinding[] { new XRBinding("Text", this.dstQuotation1, "dtQuotation.SINGS") };
            //this.xrTableCell15.DataBindings.AddRange(bindingArray14);
            this.xrTableCell15.Dpi = 254f;
            this.xrTableCell15.Font = new Font("Calibri", 9f);
            this.xrTableCell15.Name = "xrTableCell15";
            this.xrTableCell15.StylePriority.UseBorders = false;
            this.xrTableCell15.StylePriority.UseFont = false;
            this.xrTableCell15.StylePriority.UseTextAlignment = false;
            this.xrTableCell15.Text = "xrTableCell15";
            this.xrTableCell15.TextAlignment = TextAlignment.MiddleCenter;
            this.xrTableCell15.Weight = 0.30701834057148786;
            XRTableCell[] cellArray10 = new XRTableCell[] { this.xrKdv, this.xrTableCell19, this.xrTableCell16 };
            this.xrTableRow4.Cells.AddRange(cellArray10);
            this.xrTableRow4.Dpi = 254f;
            this.xrTableRow4.Name = "xrTableRow4";
            this.xrTableRow4.Weight = 1.0;
            this.xrKdv.Dpi = 254f;
            this.xrKdv.Font = new Font("Calibri", 9f, FontStyle.Bold);
            this.xrKdv.Name = "xrKdv";
            this.xrKdv.StylePriority.UseFont = false;
            this.xrKdv.Text = "KDV     %18";
            this.xrKdv.Weight = 1.4307129300313002;
            this.xrTableCell19.Borders = BorderSide.Bottom | BorderSide.Left;
            this.xrTableCell19.BorderWidth = 1f;
            this.xrTableCell19.Dpi = 254f;
            this.xrTableCell19.Font = new Font("Calibri", 9f);
            this.xrTableCell19.Name = "xrTableCell19";
            this.xrTableCell19.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrTableCell19.StylePriority.UseBorders = false;
            this.xrTableCell19.StylePriority.UseBorderWidth = false;
            this.xrTableCell19.StylePriority.UseFont = false;
            this.xrTableCell19.StylePriority.UsePadding = false;
            this.xrTableCell19.StylePriority.UseTextAlignment = false;
            summary3.FormatString = "{0:n}";
            this.xrTableCell19.Summary = summary3;
            this.xrTableCell19.Text = "xrTableCell19";
            this.xrTableCell19.TextAlignment = TextAlignment.MiddleRight;
            this.xrTableCell19.Weight = 1.2622687293972121;
            this.xrTableCell16.Borders = BorderSide.Bottom | BorderSide.Right;
            XRBinding[] bindingArray15 = new XRBinding[] { new XRBinding("Text", this.dstQuotation1, "dtQuotation.SINGS") };
            //this.xrTableCell16.DataBindings.AddRange(bindingArray15);
            this.xrTableCell16.Dpi = 254f;
            this.xrTableCell16.Font = new Font("Calibri", 9f);
            this.xrTableCell16.Name = "xrTableCell16";
            this.xrTableCell16.StylePriority.UseBorders = false;
            this.xrTableCell16.StylePriority.UseFont = false;
            this.xrTableCell16.StylePriority.UseTextAlignment = false;
            this.xrTableCell16.Text = "xrTableCell16";
            this.xrTableCell16.TextAlignment = TextAlignment.MiddleCenter;
            this.xrTableCell16.Weight = 0.30701834057148786;
            this.xrTableRow5.BackColor = Color.LightGray;
            XRTableCell[] cellArray11 = new XRTableCell[] { this.xrBrut, this.xrTableCell20, this.xrTableCell18 };
            this.xrTableRow5.Cells.AddRange(cellArray11);
            this.xrTableRow5.Dpi = 254f;
            this.xrTableRow5.Name = "xrTableRow5";
            this.xrTableRow5.StylePriority.UseBackColor = false;
            this.xrTableRow5.Weight = 1.3628569684709821;
            this.xrBrut.Dpi = 254f;
            this.xrBrut.Font = new Font("Calibri", 9f, FontStyle.Bold);
            this.xrBrut.Name = "xrBrut";
            this.xrBrut.StylePriority.UseFont = false;
            this.xrBrut.Text = "BR\x00dcT TOPLAM";
            this.xrBrut.Weight = 1.4307129300313002;
            this.xrTableCell20.Borders = BorderSide.Bottom | BorderSide.Left;
            this.xrTableCell20.BorderWidth = 1f;
            this.xrTableCell20.Dpi = 254f;
            this.xrTableCell20.Font = new Font("Calibri", 9f, FontStyle.Bold);
            this.xrTableCell20.Name = "xrTableCell20";
            this.xrTableCell20.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrTableCell20.StylePriority.UseBorders = false;
            this.xrTableCell20.StylePriority.UseBorderWidth = false;
            this.xrTableCell20.StylePriority.UseFont = false;
            this.xrTableCell20.StylePriority.UsePadding = false;
            this.xrTableCell20.StylePriority.UseTextAlignment = false;
            summary4.FormatString = "{0:n}";
            this.xrTableCell20.Summary = summary4;
            this.xrTableCell20.Text = "xrTableCell20";
            this.xrTableCell20.TextAlignment = TextAlignment.MiddleRight;
            this.xrTableCell20.Weight = 1.2622687293972121;
            this.xrTableCell20.WordWrap = false;
            this.xrTableCell18.Borders = BorderSide.Bottom | BorderSide.Right;
            XRBinding[] bindingArray16 = new XRBinding[] { new XRBinding("Text", this.dstQuotation1, "dtQuotation.SINGS") };
            //this.xrTableCell18.DataBindings.AddRange(bindingArray16);
            this.xrTableCell18.Dpi = 254f;
            this.xrTableCell18.Font = new Font("Calibri", 9f, FontStyle.Bold);
            this.xrTableCell18.Name = "xrTableCell18";
            this.xrTableCell18.StylePriority.UseBorders = false;
            this.xrTableCell18.StylePriority.UseFont = false;
            this.xrTableCell18.StylePriority.UseTextAlignment = false;
            this.xrTableCell18.Text = "xrTableCell18";
            this.xrTableCell18.TextAlignment = TextAlignment.MiddleCenter;
            this.xrTableCell18.Weight = 0.30701834057148786;
            this.xrLabel37.Dpi = 254f;
            this.xrLabel37.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.xrLabel37.LocationFloat = new PointFloat(0f, 108.0833f);
            this.xrLabel37.Multiline = true;
            this.xrLabel37.Name = "xrLabel37";
            this.xrLabel37.Padding = new PaddingInfo(5, 5, 10, 0, 254f);
            this.xrLabel37.SizeF = new SizeF(1750f, 49.18684f);
            this.xrLabel37.StylePriority.UseFont = false;
            this.xrLabel37.StylePriority.UsePadding = false;
            this.xrLabel37.StylePriority.UseTextAlignment = false;
            this.xrLabel37.Text = "IME GENERAL COMPONENTS ELEKTRİK ELEKTRONİK İTHALAT VE İHRACAT LTD. ŞTİ. BANKA HESAP NUMARALARI : \r\n";
            this.xrLabel37.TextAlignment = TextAlignment.TopLeft;
            this.xrOdemeSekli_.Dpi = 254f;
            this.xrOdemeSekli_.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.xrOdemeSekli_.LocationFloat = new PointFloat(278.2051f, 62.93747f);
            this.xrOdemeSekli_.Name = "xrOdemeSekli_";
            this.xrOdemeSekli_.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrOdemeSekli_.SizeF = new SizeF(276.3263f, 38.43743f);
            this.xrOdemeSekli_.StylePriority.UseFont = false;
            this.xrOdemeSekli_.StylePriority.UseTextAlignment = false;
            this.xrOdemeSekli_.Text = "\x00d6deme Şekli";
            this.xrOdemeSekli_.TextAlignment = TextAlignment.MiddleLeft;
            this.xrLabel32.Dpi = 254f;
            this.xrLabel32.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.xrLabel32.LocationFloat = new PointFloat(234.6879f, 62.93747f);
            this.xrLabel32.Name = "xrLabel32";
            this.xrLabel32.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrLabel32.SizeF = new SizeF(16.51736f, 38.43743f);
            this.xrLabel32.StylePriority.UseFont = false;
            this.xrLabel32.StylePriority.UseTextAlignment = false;
            this.xrLabel32.Text = ":";
            this.xrLabel32.TextAlignment = TextAlignment.MiddleLeft;
            this.xrOdemeSekli.Dpi = 254f;
            this.xrOdemeSekli.Font = new Font("Calibri", 8f, FontStyle.Bold);
            this.xrOdemeSekli.LocationFloat = new PointFloat(3.814697E-05f, 62.93747f);
            this.xrOdemeSekli.Name = "xrOdemeSekli";
            this.xrOdemeSekli.Padding = new PaddingInfo(5, 5, 0, 0, 254f);
            this.xrOdemeSekli.SizeF = new SizeF(234.6877f, 38.43743f);
            this.xrOdemeSekli.StylePriority.UseFont = false;
            this.xrOdemeSekli.StylePriority.UseTextAlignment = false;
            this.xrOdemeSekli.Text = "\x00d6deme Şekli";
            this.xrOdemeSekli.TextAlignment = TextAlignment.MiddleLeft;
            Band[] bands = new Band[] { this.Detail1, this.GroupHeader2 };
            this.DetailReport.Bands.AddRange(bands);
            this.DetailReport.DataMember = "dtQuotation";
            this.DetailReport.DataSource = this.dstQuotation1;
            this.DetailReport.Dpi = 254f;
            this.DetailReport.Level = 0;
            this.DetailReport.Name = "DetailReport";
            XRControl[] controlArray6 = new XRControl[] { this.xrTable4 };
            this.Detail1.Controls.AddRange(controlArray6);
            this.Detail1.Dpi = 254f;
            this.Detail1.HeightF = 50.00002f;
            this.Detail1.Name = "Detail1";
            XRControl[] controlArray7 = new XRControl[] { this.xrTable1 };
            this.GroupHeader2.Controls.AddRange(controlArray7);
            this.GroupHeader2.Dpi = 254f;
            this.GroupHeader2.HeightF = 101.4792f;
            this.GroupHeader2.Name = "GroupHeader2";
            Band[] bandArray2 = new Band[] { this.Detail, this.TopMargin, this.BottomMargin, this.PageHeader, this.PageFooter, this.GroupHeader1, this.ReportFooter, this.DetailReport };
            base.Bands.AddRange(bandArray2);
            base.DesignerOptions.ShowPrintingWarnings = false;
            this.Dpi = 254f;
            base.Margins = new Margins(0x62, 0x72, 0x6a, 0x49);
            base.PageHeight = 0x834;
            base.PageWidth = 0xb9a;
            base.PaperKind = PaperKind.A4Rotated;
            base.ReportUnit = ReportUnit.TenthsOfAMillimeter;
            base.SnapGridSize = 31.75f;
            base.Version = "15.2";
            this.xrTable4.EndInit();
            this.xrTable1.EndInit();
            this.dstQuotation1.EndInit();
            this.xrTable5.EndInit();
            this.xrTable2.EndInit();
            this.xrTable3.EndInit();
            this.EndInit();
        }
    }
}

