using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LoginForm.Services.MyClasses
{
    class MyAuthority
    {
        public enum IMEAuthority
        {
            ChangeUserAuthorizations = 1018,
            ViewCostandMargininQuotationModule =1020,
            ViewTotalMarge=1021,
            ViewLoaderModule=1022,
            ViewWorkToBeModule=1023,
            ViewManagementModule=1024,
            ViewCustomerModule=1089,
            AddCustomer=1090,
            EditCustomer=1091,
            ViewPurchaseOrderModule=1092,
            AddPurchaseOrder=1093,
            ViewSupplierModule=1094,
            AddSupplier=1095,
            EditSupplier=1096,
            ViewUserModule=1097,
            UpdateItemCardModule=1100,
            ViewAllBreakPointPricesinItemCard=1101,
            AddNoteinItemCard=1102,
            EditNoteinItemCard=1103,
            ViewSaleOrderModule=1104,
            AddSaleOrderModule=1105,
            EditLowMarginLimit=1107,
            EditVAT=1108,
            EditDefaultCurrency=1109,
            EditFactor=1110,
            EditDataSeperator=1111,
            EditDataBranchCode=1112,
            EditDataExchangeRate=1113,
            EditSaleOrderModule = 1164,
            ViewLicencedArticles = 1115,
            ViewDiscontinuedList=1116,
            ViewSlidingPriceList=1117,
            ViewHazardousArticlesFileStrucure=1118,
            ViewStockLevelReport=1119,
            ViewOrderAcknowledgement=1120,
            ViewQuotationModule=1121,
            EditTermsofPayment=1122,
            EditRolesAndAuthorities=1123,
            EditCategoryAndSubCategory=1124,
            EditanyQuotation=1125,
            DeleteQuotation=1126,
            AddQuotation=1127,
            ViewStockModule=1128,
            ViewInvoiceModule=1129,
            ViewExchangeRate=1130,
            ViewTermsofPayment=1131,
            ViewCategoryAndSubCategory = 1132,
            ViewRolesandAuthorities = 1133,
            ViewManagementControl = 1134,
            ViewCustomerTransfer = 1135,
            ViewRsInvoice = 1136,
            ViewSuperDisk = 1137,
            ViewSuperDiskP = 1138,
            ViewSlidingPrice = 1139,
            ViewHazardouse = 1140,
            ViewRsProList = 1141,
            ViewTSEList = 1142,
            ViewDualUsedArticles = 1143,
            ViewExtendedRangePrice = 1144,
            ViewDiscountinuedList = 1145,
            ViewOnSale = 1146,
            ViewOrderAcknowledgemenet = 1147,
            ViewBackOrder = 1148,
            ViewMargine = 1149,
            ViewCost = 1150,
            ViewExcel = 1151,
            ViewUKPrice = 1152,
            ViewLandingCost = 1153,
            ViewDiscount = 1154,
            ViewSubTotal = 1155,
            ViewTotalMargine = 1156,
            ViewTotalCost = 1157,
            ViewQuotationCheckBox = 1158,
            EditItemCard = 1159,
            AddItemCard = 1160,
            RevisionQuotation = 1161,
            ViewMailParametersPurchaseOrder = 1162,
            AddRsInvoice = 1163,
            DeleteSaleOrderModule = 1164
        }
    }
}
